name: Deploy to Server via FTP
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    
    - name: Deploy to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./
        server-dir: /var/www/html/
        exclude: |
          **/.git*
          **/.git*/**
          **/.env*
          **/.github/**
        
    - name: Deployment completed
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Tag: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
