name: Deploy to Server via FTP
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Verify tag is from main branch
      run: |
        # Get the commit hash of the tag
        TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
        
        # Get the commit hash of main branch
        MAIN_COMMIT=$(git rev-parse origin/main)
        
        # Check if tag commit is reachable from main
        if ! git merge-base --is-ancestor $TAG_COMMIT origin/main; then
          echo "Tag ${{ github.ref_name }} is not from main branch"
          exit 1
        fi
        
        echo "Tag ${{ github.ref_name }} verified to be from main branch"
    
    - name: Deploy to server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: sftp
        port: 21
        local-dir: ./
        server-dir: /var/www/html/
        exclude: |
          **/.git*
          **/.git*/**
          **/.env*
          **/.github/**
        
    - name: Deployment completed
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Tag: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
